### ISSUE TITLE
TypeError: parent.endsWith is not a function

### ISSUE THREAD

**Issue by pgonzale60** [blobtoolkit/viewer#1]
Hi Rich,

I've installed the viewer and its dependencies. When launching `npm run api` I get the error

> TypeError: parent.endsWith is not a function

 ([948Z-debug.log](https://github.com/blobtoolkit/viewer/files/3566457/2019-09-02T13_59_21_948Z-debug.log)). I suspect that would happen in the case that the "parent" variable is null. This is a fresh installation and so I guess the data it is trying to pull comes from the demo folder. I tried using my own data, but I get the same error.

How can I get the viewer running from here?

**Comment by rjchallis** [comment]
Hi Pablo

This is happening in a function that tries to load a tree of datasets,
which is used on the public instance but needs specific metadata so
shouldn't be loaded by default.

I think this is happening because an environment variable in the `.env`
file (`BTK_DATASET_TABLE=true`) has a default value of true when it should
be unset. Could you try loading the API with that line deleted and,
assuming it works, I'll update `.env.dist` so it is no longer the default.

Thanks

Rich

**Comment by pgonzale60** [comment]
Hi Rich,

Indeed! It works after deleting the line declaring BTK_DATASET_TABLE. 

Thanks!

Pablo

**Comment by rjchallis** [comment]
Thanks for confirming that it was the environment variable causing the problem
