### ISSUE TITLE
[v2.6.2] Plot Connected Windows has lines all over and outside of plot margins

### ISSUE THREAD

**Issue by kubu4** [blobtoolkit/viewer#22]
I'm trying to view my data (local assembly pipeline) with the "Plot Connected Windows" view in the "Settings" tab. But, this is what it looks like:

![image](https://user-images.githubusercontent.com/4514104/128208852-9e55ff30-b046-46ac-a4ba-d3586bbedd23.png)

If you'd like, you can download all of the `.json` files from this directory:

https://gannet.fish.washington.edu/Atumefaciens/20210712_pgen_blobtools_Panopea-generosa-v1.0/blobtools/Panopea_generosa_v1/

**Comment by rjchallis** [comment]
Thanks for sharing the files, they were really useful for working this out. The problem here is that your assembly contiguity is better than any that I have tested on!

This plot uses the same scaling as the standard blob plots, which has been fine for all the chromosomal assemblies I have tried it on, but I realise now that all of these still contained some smaller fragments that had not been assigned to chromosomes. As your dataset has none of these smaller fragments, the range of values for the assembled molecules is very small and the variation in values when these are chopped into smaller sections is inevitably greater than when the values are averaged out across whole chromosomes.

I need to add a function to rescale the axes for the window plots so the view will automatically zoom out rather than presenting the chaos that you see here. Playing with the scales makes the plot a little more sensible, e.g.: http://localhost:8080/view/Panopea_generosa_v1/dataset/Panopea_generosa_v1/blob?plotShape=lines&reads_cov--LimitMin=200&reads_cov--LimitMax=600&gc--LimitMin=0.24&gc--LimitMax=0.32#Settings, but the circles are still missing as the length scale can't be changed in the url, editing meta.json line 31 to divide the lower limit of the range by 10 (`"range": [2773746, 89643857],`) restores the circles to the plot, so I think I know what the code needs to do to make this plot behave.

![Panopea_generosa_v1 blob lines](https://user-images.githubusercontent.com/6704492/128844849-aebb4e96-8b34-4ffe-bb4d-b8974650df47.png)
